### ISSUE TITLE
Deprecated selector in `indent-guide-ext/styles/indent-guide-ext.less`

### ISSUE THREAD

**Issue by masiqbal** [SKAhack/indent-guide-ext#3]
In `indent-guide-ext/styles/indent-guide-ext.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .hard-tab.indent-guide` => `atom-text-editor.editor .hard-tab.indent-guide`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by skahack** [comment]
fixed 🙏  v0.2.2
